"""add expense category

Revision ID: 5a7fb6d98b2f
Revises: 68fafd44b3fa
Create Date: 2026-09-14 19:39:47.783929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7fb6d98b2f'
down_revision: Union[str, Sequence[str], None] = '68fafd44b3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('expense_category', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'expense_category')
    # ### end Alembic commands ###
