"""add all expense tracker tables

Revision ID: 7ead5ac6d1b5
Revises: 78b84a35e0ee
Create Date: 2026-09-08 19:04:36.344478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ead5ac6d1b5'
down_revision: Union[str, Sequence[str], None] = '78b84a35e0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
